# Dependencies
markdown:         kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            MTurgeon
tagline:          'Maxime Turgeon'
description:      'My personal webpage'
url:              http://turgeonmaxime.github.io
baseurl:	  '/'
encoding: 	  utf-8

author:
  name:           'Maxime Turgeon'
  email:	  maxime.turgeon@mail.mcgill.ca
  url:            http://turgeonmaxime.github.io
  github:         turgeonmaxime
  twitter:        mturg1989

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/turgeonmaxime/turgeonmaxime.github.io

excerpt_separator: <!--more-->
